pipeline {
    agent any
    environment {
        DJANGO_SETTINGS_MODULE = 'todo.settings'
        DOCKER_IMAGE = 'todo'
        REGISTRY_CREDENTIALS = credentials('dckr_pat_reOJBlnx35SI4QFuvkKkkns3cdUs')
    }
    stages {
        stage('Install Dependencies') {
            steps {
                bat 'pip install -r requirements.txt'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("$DOCKER_IMAGE:${env.BUILD_ID}")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'REGISTRY_CREDENTIALS') {
                        docker.image("$DOCKER_IMAGE:${env.BUILD_ID}").push('latest')
                    }
                }
            }
        }
    }
}
